apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-cd-app
spec:
  selector:
    matchLabels:
      app: desafio-cd-app

  template:
    metadata:
      labels:
        app: desafio-cd-app
    spec:
      containers:
        - name: desafio-cd-app
          image: img-app-deployment
          ports:
            - containerPort: 8003

---

apiVersion: v1
kind: Service
metadata:
  name: desafio-cd-service-app
  labels:
    app: desafio-cd-service-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8003
  selector:
    app: desafio-cd-app
