FROM golang:alpine AS builder

WORKDIR /src/app
RUN apk add git

COPY ./src/app.go .

RUN go get -d -v \
 && GOOS=linux go build -ldflags="-s -w" app.go \
 && chmod +x app

FROM scratch
COPY --from=builder /src/app/app /bin/app

ENTRYPOINT ["/bin/app"]